apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeel-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      site: cafeel
  template:
    metadata:
      labels:
        site: cafeel
    spec:
      containers:
        - name: site
          image: mariogalaviz/cafeel-site
          ports:
          - containerPort: 3008